export const ResData = [
  {
    info: {
      id: "293211",
      name: "Hotel Venus",
      cloudinaryImageId: "s8qangtphdyh4delzabz",
      locality: "Fajalpur Maholla",
      areaName: "Shiv Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Chinese", "Indian"],
      parentId: "103288",
      avgRatingString: "--",
      sla: {
        deliveryTime: 49,
        lastMileTravel: 8.6,
        serviceability: "SERVICEABLE",
        slaString: "49 mins",
        lastMileTravelString: "8.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 23:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/hotel-venus-fajalpur-maholla-shiv-nagar-rudrapur-293211",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "212513",
      name: "Hotel Amber",
      cloudinaryImageId: "esd4en7ro5xwsetwcxzp",
      locality: "Kashipur Bypass Road",
      areaName: "Rudrapur Locality",
      costForTwo: "₹350 for two",
      cuisines: ["North Indian", "Snacks"],
      avgRating: 4.3,
      parentId: "97894",
      avgRatingString: "4.3",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 52,
        lastMileTravel: 6.6,
        serviceability: "SERVICEABLE",
        slaString: "52 mins",
        lastMileTravelString: "6.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 23:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/hotel-amber-kashipur-bypass-road-rudrapur-locality-rudrapur-212513",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "547473",
      name: "Pappu Da Dhaba",
      cloudinaryImageId: "n1eldwada8x6ijqmvl9f",
      locality: "Shiv Nagar",
      areaName: "Rudrapur Locality",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian"],
      avgRating: 4.3,
      veg: true,
      parentId: "155014",
      avgRatingString: "4.3",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 39,
        lastMileTravel: 5.9,
        serviceability: "SERVICEABLE",
        slaString: "39 mins",
        lastMileTravelString: "5.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 16:50:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/pappu-da-dhaba-shiv-nagar-rudrapur-locality-rudrapur-547473",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "679153",
      name: "Shiv Restaurant",
      cloudinaryImageId: "6dbf749b863c540b56738db880a6c733",
      locality: "U.s nagar",
      areaName: "Shiv Nagar",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian"],
      parentId: "15748",
      avgRatingString: "--",
      sla: {
        deliveryTime: 46,
        lastMileTravel: 6.4,
        serviceability: "SERVICEABLE",
        slaString: "46 mins",
        lastMileTravelString: "6.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 23:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/shiv-restaurant-u-s-nagar-shiv-nagar-rudrapur-679153",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "678153",
      name: "Kouzina Kafe - The Food Court",
      cloudinaryImageId: "a92eada783210c82b133ec9fdfe574e2",
      locality: "Udham Singh Nagar",
      areaName: "Shiv Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Desserts", "Ice Cream", "Snacks", "Burgers"],
      avgRating: 3.3,
      parentId: "249027",
      avgRatingString: "3.3",
      totalRatingsString: "4",
      sla: {
        deliveryTime: 39,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "39 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-26 00:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/kouzina-kafe-the-food-court-udham-singh-nagar-shiv-nagar-rudrapur-678153",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "582694",
      name: "Punjabi Kitchen",
      cloudinaryImageId: "l0wxxucikkhcqodjgl0w",
      locality: "National Highway 87",
      areaName: "Shiv Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Biryani", "Indian"],
      avgRating: 4.6,
      veg: true,
      parentId: "738",
      avgRatingString: "4.6",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 46,
        lastMileTravel: 5.9,
        serviceability: "SERVICEABLE",
        slaString: "46 mins",
        lastMileTravelString: "5.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 16:05:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/punjabi-kitchen-national-highway-87-shiv-nagar-rudrapur-582694",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "678154",
      name: "Burger It Up",
      cloudinaryImageId: "a40cbb1d3303422319d9293272c40730",
      locality: "Rudrapur",
      areaName: "Shiv Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Burgers", "Desserts", "American", "Beverages"],
      avgRating: 3.3,
      parentId: "7864",
      avgRatingString: "3.3",
      totalRatingsString: "7",
      sla: {
        deliveryTime: 39,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "39 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-26 00:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/burger-it-up-shiv-nagar-rudrapur-678154",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "677964",
      name: "Kaati Zone Rolls & Wraps",
      cloudinaryImageId: "e0776c6fb336fd3bbe7381c59ab0a469",
      locality: "Rudrapur",
      areaName: "Shiv Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Snacks", "Fast Food", "Desserts", "Beverages"],
      avgRating: 4.2,
      parentId: "248306",
      avgRatingString: "4.2",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 37,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "37 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-26 00:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "UPTO ₹75",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/kaati-zone-rolls-and-wraps-shiv-nagar-rudrapur-677964",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "678005",
      name: "Indiana Burgers",
      cloudinaryImageId: "8d3e4da8ceef599a8866b714dcb72e51",
      locality: "Rudrapur",
      areaName: "Shiv Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Burgers", "Snacks", "Desserts", "Beverages"],
      avgRating: 4,
      parentId: "5714",
      avgRatingString: "4.0",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 39,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "39 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-26 00:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "UPTO ₹75",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/indiana-burgers-shiv-nagar-rudrapur-678005",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "677975",
      name: "Slurpy Shakes",
      cloudinaryImageId: "5bba28b6d43eebd9cafa2ff61bead8ad",
      locality: "Rudrapur",
      areaName: "Shiv Nagar",
      costForTwo: "₹150 for two",
      cuisines: ["Ice Cream", "Desserts", "Beverages"],
      avgRating: 4.1,
      veg: true,
      parentId: "5713",
      avgRatingString: "4.1",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 42,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "42 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-26 00:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/slurpy-shakes-shiv-nagar-rudrapur-677975",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "345559",
      name: "Chatore",
      cloudinaryImageId: "dsbaooaqhda72mtjojzy",
      locality: "balaji board walk",
      areaName: "Lamara",
      costForTwo: "₹300 for two",
      cuisines: ["Indian"],
      avgRating: 3.8,
      parentId: "58518",
      avgRatingString: "3.8",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 46,
        lastMileTravel: 6.1,
        serviceability: "SERVICEABLE",
        slaString: "46 mins",
        lastMileTravelString: "6.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 22:57:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/chatore-balaji-board-walk-lamara-rudrapur-345559",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "418606",
      name: "The Chocolate Room",
      cloudinaryImageId: "jpynxfkx29qyd7u7xxlp",
      locality: "Udham Singh Nagar",
      areaName: "Shiv Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["Continental", "Snacks", "Desserts", "Beverages"],
      avgRating: 4,
      parentId: "1002",
      avgRatingString: "4.0",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 48,
        lastMileTravel: 6.7,
        serviceability: "SERVICEABLE",
        slaString: "48 mins",
        lastMileTravelString: "6.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 23:00:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹40",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/the-chocolate-room-udham-singh-nagar-shiv-nagar-rudrapur-418606",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "790659",
      name: "Hungry Point",
      cloudinaryImageId: "414d3d3f11fb6f320788ac6b7c706e01",
      locality: "Udham Singh Nagar",
      areaName: "Shiv Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Pizzas", "Snacks", "Beverages"],
      parentId: "5290",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 40,
        lastMileTravel: 6,
        serviceability: "SERVICEABLE",
        slaString: "40 mins",
        lastMileTravelString: "6.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 23:15:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/hungry-point-udham-singh-nagar-shiv-nagar-rudrapur-790659",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "412595",
      name: "Punjabi Tadka",
      cloudinaryImageId: "qnnilwilw9kdsozjrpui",
      locality: "Malik Colony",
      areaName: "Shiv Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["North Indian"],
      avgRating: 3.7,
      veg: true,
      parentId: "435887",
      avgRatingString: "3.7",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 54,
        lastMileTravel: 7.8,
        serviceability: "SERVICEABLE",
        slaString: "54 mins",
        lastMileTravelString: "7.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 23:59:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/punjabi-tadka-malik-colony-shiv-nagar-rudrapur-412595",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "720096",
      name: "Mom's Kitchen",
      cloudinaryImageId: "3d3bfc207da6c760c676a93c36466d55",
      locality: "Saraswati enclave",
      areaName: "Shiv Nagar",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian", "Snacks", "Thalis"],
      avgRating: 4.2,
      veg: true,
      parentId: "2594",
      avgRatingString: "4.2",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 59,
        lastMileTravel: 8.2,
        serviceability: "SERVICEABLE",
        slaString: "59 mins",
        lastMileTravelString: "8.2 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-12-25 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-704a0b0a-020e-4ad5-aad0-e5f69e849a5e",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/moms-kitchen-saraswati-enclave-shiv-nagar-rudrapur-720096",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
];
